parameters:
  SolutionBaseName:
  BuildConfiguration:

jobs:
- job: CodeBuild
  dependsOn: DacpacBuild
  pool:
    name: DAS - Continuous Integration Agents
    workspace:
      clean: all
  variables:
  - group: BUILD Management Resources
  steps:

  # - task: DockerInstaller@0
  #   displayName: 'Install Docker'

  - bash: |
      sudo apt-get update
      sudo apt-get install docker
      sudo systemctl docker start
    displayName: 'Start Docker'

  - task: Docker@2
    inputs:
      command: 'pull'
      arguments: 'mcr.microsoft.com/mssql/server'

  - task: Docker@2
    inputs:
      command: 'run'
      arguments: '-e "ACCEPT_EULA=Y" -e "SA_PASSWORD=P1peline" -p 1433:1433 --name sql_server_container -d mcr.microsoft.com/mssql/server'

  - bash: |
      sudo npm install -g azurite
      sudo mkdir azurite
      sudo azurite --silent --location azurite --debug azurite\debug.log &
    displayName: 'Install and Run Azurite'

  - template: azure-pipelines-templates/build/step/gitversion.yml@das-platform-building-blocks

  - task: DownloadBuildArtifacts@1
    displayName: Download Dacpac For Acceptance Tests
    inputs:
      buildType: 'current' # 'current' | 'specific'. Required. Download artifacts produced by. Default: current.
      downloadType: 'specific' # 'single' | 'specific'. Required. Download type. Default: single.
      downloadPath: '$(build.artifactstagingdirectory)/download'

  - task: CopyFiles@2
    displayName: Copy Dacpac For Acceptance Tests
    inputs:
      Contents: '**'
      TargetFolder: 'src/Database/bin/release'
      flattenFolders : true
      SourceFolder : '$(build.artifactstagingdirectory)/download'



  - template: azure-pipelines-templates/build/step/app-build.yml@das-platform-building-blocks
    parameters:
      RunAcceptanceTests: true
      ContinueOnVulnerablePackageScanError: true # TEMP - DO NOT APPROVE PR WITH THIS IN PLACE

  - powershell: |
      Get-ChildItem -Path $(Build.SourcesDirectory) -Recurse -Name
    displayName: 'List Folder Contents SourcesDirectory $(Build.SourcesDirectory)'

  - task: DotNetCoreCLI@2
    displayName: Publish - dotnet publish Inner Api
    inputs:
      command: publish
      publishWebProjects: false #set to false as this setting (which defaults to true) will parse the entire repo for web projects
      projects: src/InnerApi/${{ parameters.SolutionBaseName }}.InnerApi.csproj
      arguments: -o $(build.artifactstagingdirectory)/publish -c ${{ parameters.BuildConfiguration }} --no-build
      modifyOutputPath: true
      zipAfterPublish: true

  - task: DotNetCoreCLI@2
    displayName: Publish - dotnet publish Durable Entities
    inputs:
      command: publish
      publishWebProjects: false #set to false as this setting (which defaults to true) will parse the entire repo for web projects
      projects: src/DurableEntities/${{ parameters.SolutionBaseName }}.DurableEntities.csproj
      arguments: -o $(build.artifactstagingdirectory)/publish -c ${{ parameters.BuildConfiguration }} --no-build
      modifyOutputPath: true
      zipAfterPublish: true

  - task: CopyFiles@2
    displayName: Copy Files to $(build.artifactstagingdirectory)/publish
    inputs:
      Contents: |
        azure/**
      TargetFolder: $(build.artifactstagingdirectory)/publish
      OverWrite: true

  - task: PublishPipelineArtifact@1
    displayName: Publish Build Artifact
    inputs:
      targetPath: $(build.artifactstagingdirectory)/publish
      artifactName: ${{ parameters.SolutionBaseName }}
  
  - template: azure-pipelines-templates/build/step/nuget-pack.yml@das-platform-building-blocks
    parameters:
      DotNetStandardPackagesToPack: |
        src/Types/${{ parameters.SolutionBaseName }}.Types.csproj;